<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.0.0" />
    <PackageReference Include="MediatR" Version="14.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="AthenaUnionLibrary">
      <HintPath>..\..\AthenaUnionLibrary\AthenaUnionLibrary\bin\Debug\net10.0\AthenaUnionLibrary.dll</HintPath>
    </Reference>
    <Reference Include="Mediator">
      <HintPath>..\..\AthenaUnionLibrary\Mediator\bin\Debug\net10.0\Mediator.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
